{"uuid": "959c39f3-524e-4ae1-bdaf-669d4c359e9e", "children": ["7d97d67c-224e-4043-9cc3-e9e13e821008"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary\nStacktrace:\n#0 0x5c6b1e2b74e3 <unknown>\n#1 0x5c6b1dfe6c76 <unknown>\n#2 0x5c6b1e00d757 <unknown>\n#3 0x5c6b1e00c029 <unknown>\n#4 0x5c6b1e04accc <unknown>\n#5 0x5c6b1e04a47f <unknown>\n#6 0x5c6b1e041de3 <unknown>\n#7 0x5c6b1e0172dd <unknown>\n#8 0x5c6b1e01834e <unknown>\n#9 0x5c6b1e2773e4 <unknown>\n#10 0x5c6b1e27b3d7 <unknown>\n#11 0x5c6b1e285b20 <unknown>\n#12 0x5c6b1e27c023 <unknown>\n#13 0x5c6b1e24a1aa <unknown>\n#14 0x5c6b1e2a06b8 <unknown>\n#15 0x5c6b1e2a0847 <unknown>\n#16 0x5c6b1e2b0243 <unknown>\n#17 0x7c091b64baa4 <unknown>\n#18 0x7c091b6d8c3c <unknown>\n\n", "trace": "  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1195, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 922, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/workspaces/selenium-automation-framework/conftest.py\", line 25, in driver\n    driver = webdriver.Chrome(service=service, options=options)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py\", line 47, in __init__\n    super().__init__(\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py\", line 69, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 257, in __init__\n    self.start_session(capabilities)\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 356, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py\", line 447, in execute\n    self.error_handler.check_response(response)\n  File \"/workspaces/selenium-automation-framework/venv/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1750916133047, "stop": 1750916133465}], "start": 1750916133047, "stop": 1750916133548}